### ISSUE TITLE
Support for deploying to heroku

### ISSUE THREAD

**Issue by Bugaddr** [diogenesc/telegram-webhook#4]
Heroku provide support for running small apps, can you make it possible to host this in heroku ?

**Comment by diogenesc** [comment]
Actually, I'm running this app on Heroku right now. A **Deploy to Heroku** button is useful to you?

**Comment by Bugaddr** [comment]
> Actually, I'm running this app on Heroku right now. A **Deploy to Heroku** button is useful to you?

Good to hear that. Yeah a button can be somewhat easy for deployment.

**Comment by diogenesc** [comment]
PR #5 implemented the button. Sorry for the delay, very busy these times :)
